// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh1izJDWZdkwdrgdVa0d48YvQV_MVP8V4',
    appId: '1:821487765809:web:46c1ff274e203a39e0c810',
    messagingSenderId: '821487765809',
    projectId: 'dislexa-f9606',
    authDomain: 'dislexa-f9606.firebaseapp.com',
    storageBucket: 'dislexa-f9606.firebasestorage.app',
    measurementId: 'G-JB9PWTWMZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABL7kiQGfA7FkCstYg1nTeLsb4ecAPOg',
    appId: '1:821487765809:android:c126c8982e97d3f1e0c810',
    messagingSenderId: '821487765809',
    projectId: 'dislexa-f9606',
    storageBucket: 'dislexa-f9606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FbFMv7qx5OR9KKrsugqEQtEVCWr6BfE',
    appId: '1:821487765809:ios:00e9c5fdd40deb55e0c810',
    messagingSenderId: '821487765809',
    projectId: 'dislexa-f9606',
    storageBucket: 'dislexa-f9606.firebasestorage.app',
    iosBundleId: 'com.lexa.disleksiSurum',
  );
}
